[15.1.3] Modified pie configuration
OntimizeWeb/ontimize-web-ngx-charts pull request #263
Opened 2024-10-08 10:01 UTC by tomfacal

Fixes #262

2024-10-08 10:59 UTC, daniel-grana requested changes

2024-10-08 10:59 UTC, daniel-grana commented on projects/ontimize-web-ngx-charts/src/lib/models/options/PieChartConfiguration.class.ts
> +  public showLeyend: boolean = false;
```suggestion
  public showLegend: boolean = false;
```

2024-10-08 14:21 UTC, patricia-martinez-imatia approved these changes

2024-10-09 07:07 UTC, daniel-grana approved these changes

2024-10-09 07:14 UTC, merged