[15.1.3] Added autoscale to line charts
OntimizeWeb/ontimize-web-ngx-charts pull request #265
Opened 2024-10-08 10:05 UTC by tomfacal

Closes #264

2024-10-08 10:58 UTC, daniel-grana submitted a review, later dismissed

2024-10-08 11:05 UTC, patricia-martinez-imatia requested changes

2024-10-08 11:05 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
> +  'autoScale'
```suggestion
  'autoScale: auto-scale'
```

2024-10-08 13:37 UTC, patricia-martinez-imatia approved these changes

2024-10-09 07:04 UTC, daniel-grana approved these changes

2024-10-09 07:05 UTC, merged